#include "languages.h"

// These abbreviated names and the language order are shared with Solar Earth.
const char day_names[LANGUAGE_COUNT][7][8] = {
    {"SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT"},
    {"DIM", "LUN", "MAR", "MER", "JEU", "VEN", "SAM"},
    {"SO", "MO", "DI", "MI", "DO", "FR", "SA"},
    {"DOM", "LUN", "MAR", "MIE", "JUE", "VIE", "SAB"},
    {"DOM", "LUN", "MAR", "MER", "GIO", "VEN", "SAB"},
    {"ZO", "MA", "DI", "WO", "DO", "VR", "ZA"},
    {"PAZ", "PTS", "SAL", "CAR", "PER", "CUM", "CTS"},
    {"NE", "PO", "UT", "ST", "CT", "PA", "SO"},
    {"DOM", "SEG", "TER", "QUA", "QUI", "SEX", "SAB"},
    {"ΚΥΡ", "ΔΕΥ", "ΤΡΙ", "ΤΕΤ", "ΠΕΜ", "ΠΑΡ", "ΣΑΒ"},
    {"SON", "MAN", "TIS", "ONS", "TOR", "FRE", "LOR"},
    {"NDZ", "PON", "WTO", "SRO", "CZW", "PIA", "SOB"},
    {"NE", "PO", "UT", "ST", "ST", "PI", "SO"},
    {"CN", "T2", "T3", "T4", "T5", "T6", "T7"},
    {"DUM", "LUN", "MAR", "MIE", "JOI", "VIN", "SAM"},
    {"DG", "DL", "DT", "DC", "DJ", "DV", "DS"},
    {"SON", "MAN", "TIR", "ONS", "TOR", "FRE", "LOR"},
    {"ВС", "ПН", "ВТ", "СР", "ЧТ", "ПТ", "СБ"},
    {"P", "E", "T", "K", "N", "R", "L"},
    {"IG", "AL", "AR", "AZ", "OG", "OL", "LR"},
    {"SU", "MA", "TI", "KE", "TO", "PE", "LA"},
    {"SON", "MAN", "TIR", "ONS", "TOR", "FRE", "LOR"},
    {"SEK", "PIR", "ANT", "TRE", "KET", "PEN", "SES"},
    {"NED", "PON", "TOR", "SRE", "CET", "PET", "SOB"},
    {"VAS", "HET", "KED", "SZE", "CSU", "PEN", "SZO"},
    {"NED", "PON", "UTO", "SRE", "CET", "PET", "SUB"},
    {"DOM", "LUA", "MAI", "CEA", "DEA", "AOI", "SAT"},
    {"SVE", "PIR", "OTR", "TRE", "CET", "PIE", "SES"},
    {"NE", "PO", "UT", "SR", "CE", "PE", "SU"},
    {"日", "一", "二", "三", "四", "五", "六"},
    {"MIN", "SEN", "SEL", "RAB", "KAM", "JUM", "SAB"},
    {"НД", "ПН", "ВТ", "СР", "ЧТ", "ПТ", "СБ"},
    {"SUL", "LLN", "MAW", "MER", "IAU", "GWE", "SAD"},
    {"DOM", "LUN", "MAR", "MER", "XOV", "VEN", "SAB"},
    {"日", "月", "火", "水", "木", "金", "土"},
    {"일", "월", "화", "수", "목", "금", "토"},
    {"א", "ב", "ג", "ד", "ה", "ו", "ש"},
    {"SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT"}};

const char month_names[LANGUAGE_COUNT][12][8] = {
    {"JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT",
     "NOV", "DEC"},
    {"JAN", "FEV", "MAR", "AVR", "MAI", "JUI", "JUL", "AOU", "SEP", "OCT",
     "NOV", "DEC"},
    {"JAN", "FEB", "MAR", "APR", "MAI", "JUN", "JUL", "AUG", "SEP", "OKT",
     "NOV", "DEZ"},
    {"ENE", "FEB", "MAR", "ABR", "MAY", "JUN", "JUL", "AGO", "SEP", "OCT",
     "NOV", "DIC"},
    {"GEN", "FEB", "MAR", "APR", "MAG", "GIU", "LUG", "AGO", "SET", "OTT",
     "NOV", "DIC"},
    {"JAN", "FEB", "MRT", "APR", "MEI", "JUN", "JUL", "AUG", "SEP", "OKT",
     "NOV", "DEC"},
    {"OCA", "SUB", "MAR", "NIS", "MAY", "HAZ", "TEM", "AGU", "EYL", "EKI",
     "KAS", "ARA"},
    {"LED", "UNO", "BRE", "DUB", "KVE", "CRV", "CVC", "SRP", "ZAR", "RIJ",
     "LIS", "PRO"},
    {"JAN", "FEV", "MAR", "ABR", "MAI", "JUN", "JUL", "AGO", "SET", "OUT",
     "NOV", "DEZ"},
    {"ΙΑΝ", "ΦΕΒ", "ΜΑΡ", "ΑΠΡ", "ΜΑΙ", "ΙΟΝ", "ΙΟΛ", "ΑΥΓ", "ΣΕΠ", "ΟΚΤ",
     "ΝΟΕ", "ΔΕΚ"},
    {"JAN", "FEB", "MAR", "APR", "MAJ", "JUN", "JUL", "AUG", "SEP", "OKT",
     "NOV", "DEC"},
    {"STY", "LUT", "MAR", "KWI", "MAJ", "CZE", "LIP", "SIE", "WRZ", "PAZ",
     "LIS", "GRU"},
    {"JAN", "FEB", "MAR", "APR", "MAJ", "JUN", "JUL", "AUG", "SEP", "OKT",
     "NOV", "DEC"},
    {"Th1", "Th2", "Th3", "Th4", "Th5", "Th6", "Th7", "Th8", "Th9", "T10",
     "T11", "T12"},
    {"IAN", "FEB", "MAR", "APR", "MAI", "IUN", "IUL", "AUG", "SEP", "OCT",
     "NOI", "DEC"},
    {"GEN", "FEB", "MAR", "ABR", "MAI", "JUN", "JUL", "AGO", "SET", "OCT",
     "NOV", "DES"},
    {"JAN", "FEB", "MAR", "APR", "MAI", "JUN", "JUL", "AUG", "SEP", "OKT",
     "NOV", "DES"},
    {"ЯНВ", "ФЕВ", "МАР", "АПР", "МАЙ", "ИЮН", "ИЮЛ", "АВГ", "СЕН", "ОКТ",
     "НОЯ", "ДЕК"},
    {"JAN", "VEB", "MAR", "APR", "MAI", "JUN", "JUL", "AUG", "SEP", "OKT",
     "NOV", "DET"},
    {"URT", "OTS", "MAR", "API", "MAI", "EKA", "UZT", "ABU", "IRA", "URR",
     "AZA", "ABE"},
    {"TAM", "HEL", "MAA", "HUH", "TOU", "KES", "HEI", "ELO", "SYY", "LOK",
     "MAR", "JOU"},
    {"JAN", "FEB", "MAR", "APR", "MAJ", "JUN", "JUL", "AUG", "SEP", "OKT",
     "NOV", "DEC"},
    {"SAU", "VAS", "KOV", "BAL", "GEG", "BIR", "LIE", "RUG", "RGS", "SPA",
     "LAP", "GRU"},
    {"JAN", "FEB", "MAR", "APR", "MAJ", "JUN", "JUL", "AVG", "SEP", "OKT",
     "NOV", "DEC"},
    {"JAN", "FEB", "MAR", "APR", "MAJ", "JUN", "JUL", "AUG", "SZE", "OKT",
     "NOV", "DEC"},
    {"SIJ", "VEL", "OZU", "TRA", "SVI", "LIP", "SRP", "KOL", "RUJ", "LIS",
     "STU", "PRO"},
    {"EAN", "FEA", "MAR", "AIB", "BEA", "MEI", "IUI", "LUN", "MFO", "DFO",
     "SAM", "NOL"},
    {"JAN", "FEB", "MAR", "APR", "MAI", "JUN", "JUL", "AUG", "SEP", "OKT",
     "NOV", "DEC"},
    {"JAN", "FEB", "MAR", "APR", "MAJ", "JUN", "JUL", "AVG", "SEP", "OKT",
     "NOV", "DEC"},
    {"1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"},
    {"JAN", "FEB", "MAR", "APR", "MEI", "JUN", "JUL", "AGU", "SEP", "OKT",
     "NOV", "DES"},
    {"СІЧ", "ЛЮТ", "БЕР", "КВІ", "ТРА", "ЧЕР", "ЛИП", "СЕР", "ВЕР", "ЖОВ",
     "ЛИС", "ГРУ"},
    {"ION", "CHW", "MAW", "EBR", "MAI", "MEH", "GOR", "AWS", "MED", "HYD",
     "TCH", "RHA"},
    {"XAN", "FEB", "MAR", "ABR", "MAI", "XUN", "XUL", "AGO", "SET", "OUT",
     "NOV", "NAD"},
    {"1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月",
     "11月", "12月"},
    {"1월", "2월", "3월", "4월", "5월", "6월", "7월", "8월", "9월", "10월",
     "11월", "12월"},
    {"ינו", "פבר", "מרץ", "אפר", "מאי", "יונ", "יול", "אוג", "ספט", "אוק",
     "נוב", "דצמ"},
    {"JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT",
     "NOV", "DEC"}};

// Full names are used only by horizontal layouts. Latin-script names follow
// the same accent-free style as the compact LECO labels above.
const char *const full_day_names[LANGUAGE_COUNT][7] = {
    {"SUNDAY", "MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY",
     "SATURDAY"},
    {"DIMANCHE", "LUNDI", "MARDI", "MERCREDI", "JEUDI", "VENDREDI",
     "SAMEDI"},
    {"SONNTAG", "MONTAG", "DIENSTAG", "MITTWOCH", "DONNERSTAG", "FREITAG",
     "SAMSTAG"},
    {"DOMINGO", "LUNES", "MARTES", "MIERCOLES", "JUEVES", "VIERNES",
     "SABADO"},
    {"DOMENICA", "LUNEDI", "MARTEDI", "MERCOLEDI", "GIOVEDI", "VENERDI",
     "SABATO"},
    {"ZONDAG", "MAANDAG", "DINSDAG", "WOENSDAG", "DONDERDAG", "VRIJDAG",
     "ZATERDAG"},
    {"PAZAR", "PAZARTESI", "SALI", "CARSAMBA", "PERSEMBE", "CUMA",
     "CUMARTESI"},
    {"NEDELE", "PONDELI", "UTERY", "STREDA", "CTVRTEK", "PATEK", "SOBOTA"},
    {"DOMINGO", "SEGUNDA-FEIRA", "TERCA-FEIRA", "QUARTA-FEIRA",
     "QUINTA-FEIRA", "SEXTA-FEIRA", "SABADO"},
    {"ΚΥΡΙΑΚΗ", "ΔΕΥΤΕΡΑ", "ΤΡΙΤΗ", "ΤΕΤΑΡΤΗ", "ΠΕΜΠΤΗ", "ΠΑΡΑΣΚΕΥΗ",
     "ΣΑΒΒΑΤΟ"},
    {"SONDAG", "MANDAG", "TISDAG", "ONSDAG", "TORSDAG", "FREDAG", "LORDAG"},
    {"NIEDZIELA", "PONIEDZIALEK", "WTOREK", "SRODA", "CZWARTEK", "PIATEK",
     "SOBOTA"},
    {"NEDELA", "PONDELOK", "UTOROK", "STREDA", "STVRTOK", "PIATOK",
     "SOBOTA"},
    {"CHU NHAT", "THU HAI", "THU BA", "THU TU", "THU NAM", "THU SAU",
     "THU BAY"},
    {"DUMINICA", "LUNI", "MARTI", "MIERCURI", "JOI", "VINERI", "SAMBATA"},
    {"DIUMENGE", "DILLUNS", "DIMARTS", "DIMECRES", "DIJOUS", "DIVENDRES",
     "DISSABTE"},
    {"SONDAG", "MANDAG", "TIRSDAG", "ONSDAG", "TORSDAG", "FREDAG", "LORDAG"},
    {"ВОСКРЕСЕНЬЕ", "ПОНЕДЕЛЬНИК", "ВТОРНИК", "СРЕДА", "ЧЕТВЕРГ",
     "ПЯТНИЦА", "СУББОТА"},
    {"PUHAPAEV", "ESMASPAEV", "TEISIPAEV", "KOLMAPAEV", "NELJAPAEV",
     "REEDE", "LAUPAEV"},
    {"IGANDEA", "ASTELEHENA", "ASTEARTEA", "ASTEAZKENA", "OSTEGUNA",
     "OSTIRALA", "LARUNBATA"},
    {"SUNNUNTAI", "MAANANTAI", "TIISTAI", "KESKIVIIKKO", "TORSTAI",
     "PERJANTAI", "LAUANTAI"},
    {"SONDAG", "MANDAG", "TIRSDAG", "ONSDAG", "TORSDAG", "FREDAG", "LORDAG"},
    {"SEKMADIENIS", "PIRMADIENIS", "ANTRADIENIS", "TRECIADIENIS",
     "KETVIRTADIENIS", "PENKTADIENIS", "SESTADIENIS"},
    {"NEDELJA", "PONEDELJEK", "TOREK", "SREDA", "CETRTEK", "PETEK",
     "SOBOTA"},
    {"VASARNAP", "HETFO", "KEDD", "SZERDA", "CSUTORTOK", "PENTEK",
     "SZOMBAT"},
    {"NEDJELJA", "PONEDJELJAK", "UTORAK", "SRIJEDA", "CETVRTAK", "PETAK",
     "SUBOTA"},
    {"DOMHNACH", "LUAN", "MAIRT", "CEADAOIN", "DEARDAOIN", "AOINE",
     "SATHARN"},
    {"SVETDIENA", "PIRMDIENA", "OTRDIENA", "TRESDIENA", "CETURTDIENA",
     "PIEKTDIENA", "SESTDIENA"},
    {"NEDELJA", "PONEDELJAK", "UTORAK", "SREDA", "CETVRTAK", "PETAK",
     "SUBOTA"},
    {"星期日", "星期一", "星期二", "星期三", "星期四", "星期五", "星期六"},
    {"MINGGU", "SENIN", "SELASA", "RABU", "KAMIS", "JUMAT", "SABTU"},
    {"НЕДІЛЯ", "ПОНЕДІЛОК", "ВІВТОРОК", "СЕРЕДА", "ЧЕТВЕР",
     "П'ЯТНИЦЯ", "СУБОТА"},
    {"DYDD SUL", "DYDD LLUN", "DYDD MAWRTH", "DYDD MERCHER", "DYDD IAU",
     "DYDD GWENER", "DYDD SADWRN"},
    {"DOMINGO", "LUNS", "MARTES", "MERCORES", "XOVES", "VENRES", "SABADO"},
    {"日曜日", "月曜日", "火曜日", "水曜日", "木曜日", "金曜日", "土曜日"},
    {"일요일", "월요일", "화요일", "수요일", "목요일", "금요일", "토요일"},
    {"יום ראשון", "יום שני", "יום שלישי", "יום רביעי", "יום חמישי",
     "יום שישי", "שבת"},
    {"SUNDAY", "MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY",
     "SATURDAY"}};

const char *const full_month_names[LANGUAGE_COUNT][12] = {
    {"JANUARY", "FEBRUARY", "MARCH", "APRIL", "MAY", "JUNE", "JULY",
     "AUGUST", "SEPTEMBER", "OCTOBER", "NOVEMBER", "DECEMBER"},
    {"JANVIER", "FEVRIER", "MARS", "AVRIL", "MAI", "JUIN", "JUILLET",
     "AOUT", "SEPTEMBRE", "OCTOBRE", "NOVEMBRE", "DECEMBRE"},
    {"JANUAR", "FEBRUAR", "MARZ", "APRIL", "MAI", "JUNI", "JULI", "AUGUST",
     "SEPTEMBER", "OKTOBER", "NOVEMBER", "DEZEMBER"},
    {"ENERO", "FEBRERO", "MARZO", "ABRIL", "MAYO", "JUNIO", "JULIO",
     "AGOSTO", "SEPTIEMBRE", "OCTUBRE", "NOVIEMBRE", "DICIEMBRE"},
    {"GENNAIO", "FEBBRAIO", "MARZO", "APRILE", "MAGGIO", "GIUGNO", "LUGLIO",
     "AGOSTO", "SETTEMBRE", "OTTOBRE", "NOVEMBRE", "DICEMBRE"},
    {"JANUARI", "FEBRUARI", "MAART", "APRIL", "MEI", "JUNI", "JULI",
     "AUGUSTUS", "SEPTEMBER", "OKTOBER", "NOVEMBER", "DECEMBER"},
    {"OCAK", "SUBAT", "MART", "NISAN", "MAYIS", "HAZIRAN", "TEMMUZ",
     "AGUSTOS", "EYLUL", "EKIM", "KASIM", "ARALIK"},
    {"LEDEN", "UNOR", "BREZEN", "DUBEN", "KVETEN", "CERVEN", "CERVENEC",
     "SRPEN", "ZARI", "RIJEN", "LISTOPAD", "PROSINEC"},
    {"JANEIRO", "FEVEREIRO", "MARCO", "ABRIL", "MAIO", "JUNHO", "JULHO",
     "AGOSTO", "SETEMBRO", "OUTUBRO", "NOVEMBRO", "DEZEMBRO"},
    {"ΙΑΝΟΥΑΡΙΟΣ", "ΦΕΒΡΟΥΑΡΙΟΣ", "ΜΑΡΤΙΟΣ", "ΑΠΡΙΛΙΟΣ", "ΜΑΙΟΣ",
     "ΙΟΥΝΙΟΣ", "ΙΟΥΛΙΟΣ", "ΑΥΓΟΥΣΤΟΣ", "ΣΕΠΤΕΜΒΡΙΟΣ", "ΟΚΤΩΒΡΙΟΣ",
     "ΝΟΕΜΒΡΙΟΣ", "ΔΕΚΕΜΒΡΙΟΣ"},
    {"JANUARI", "FEBRUARI", "MARS", "APRIL", "MAJ", "JUNI", "JULI",
     "AUGUSTI", "SEPTEMBER", "OKTOBER", "NOVEMBER", "DECEMBER"},
    {"STYCZEN", "LUTY", "MARZEC", "KWIECIEN", "MAJ", "CZERWIEC", "LIPIEC",
     "SIERPIEN", "WRZESIEN", "PAZDZIERNIK", "LISTOPAD", "GRUDZIEN"},
    {"JANUAR", "FEBRUAR", "MAREC", "APRIL", "MAJ", "JUN", "JUL", "AUGUST",
     "SEPTEMBER", "OKTOBER", "NOVEMBER", "DECEMBER"},
    {"THANG MOT", "THANG HAI", "THANG BA", "THANG TU", "THANG NAM",
     "THANG SAU", "THANG BAY", "THANG TAM", "THANG CHIN", "THANG MUOI",
     "THANG MUOI MOT", "THANG MUOI HAI"},
    {"IANUARIE", "FEBRUARIE", "MARTIE", "APRILIE", "MAI", "IUNIE", "IULIE",
     "AUGUST", "SEPTEMBRIE", "OCTOMBRIE", "NOIEMBRIE", "DECEMBRIE"},
    {"GENER", "FEBRER", "MARC", "ABRIL", "MAIG", "JUNY", "JULIOL", "AGOST",
     "SETEMBRE", "OCTUBRE", "NOVEMBRE", "DESEMBRE"},
    {"JANUAR", "FEBRUAR", "MARS", "APRIL", "MAI", "JUNI", "JULI", "AUGUST",
     "SEPTEMBER", "OKTOBER", "NOVEMBER", "DESEMBER"},
    {"ЯНВАРЬ", "ФЕВРАЛЬ", "МАРТ", "АПРЕЛЬ", "МАЙ", "ИЮНЬ", "ИЮЛЬ",
     "АВГУСТ", "СЕНТЯБРЬ", "ОКТЯБРЬ", "НОЯБРЬ", "ДЕКАБРЬ"},
    {"JAANUAR", "VEEBRUAR", "MARTS", "APRILL", "MAI", "JUUNI", "JUULI",
     "AUGUST", "SEPTEMBER", "OKTOOBER", "NOVEMBER", "DETSEMBER"},
    {"URTARRILA", "OTSAILA", "MARTXOA", "APIRILA", "MAIATZA", "EKAINA",
     "UZTAILA", "ABUZTUA", "IRAILA", "URRIA", "AZAROA", "ABENDUA"},
    {"TAMMIKUU", "HELMIKUU", "MAALISKUU", "HUHTIKUU", "TOUKOKUU", "KESAKUU",
     "HEINAKUU", "ELOKUU", "SYYSKUU", "LOKAKUU", "MARRASKUU", "JOULUKUU"},
    {"JANUAR", "FEBRUAR", "MARTS", "APRIL", "MAJ", "JUNI", "JULI", "AUGUST",
     "SEPTEMBER", "OKTOBER", "NOVEMBER", "DECEMBER"},
    {"SAUSIS", "VASARIS", "KOVAS", "BALANDIS", "GEGUZE", "BIRZELIS", "LIEPA",
     "RUGPJUTIS", "RUGSEJIS", "SPALIS", "LAPKRITIS", "GRUODIS"},
    {"JANUAR", "FEBRUAR", "MAREC", "APRIL", "MAJ", "JUNIJ", "JULIJ", "AVGUST",
     "SEPTEMBER", "OKTOBER", "NOVEMBER", "DECEMBER"},
    {"JANUAR", "FEBRUAR", "MARCIUS", "APRILIS", "MAJUS", "JUNIUS", "JULIUS",
     "AUGUSZTUS", "SZEPTEMBER", "OKTOBER", "NOVEMBER", "DECEMBER"},
    {"SIJECANJ", "VELJACA", "OZUJAK", "TRAVANJ", "SVIBANJ", "LIPANJ",
     "SRPANJ", "KOLOVOZ", "RUJAN", "LISTOPAD", "STUDENI", "PROSINAC"},
    {"EANAIR", "FEABHRA", "MARTA", "AIBREAN", "BEALTAINE", "MEITHEAMH",
     "IUIL", "LUNASA", "MEAN FOMHAIR", "DEIREADH FOMHAIR", "SAMHAIN",
     "NOLLAIG"},
    {"JANVARIS", "FEBRUARIS", "MARTS", "APRILIS", "MAIJS", "JUNIJS",
     "JULIJS", "AUGUSTS", "SEPTEMBRIS", "OKTOBRIS", "NOVEMBRIS",
     "DECEMBRIS"},
    {"JANUAR", "FEBRUAR", "MART", "APRIL", "MAJ", "JUN", "JUL", "AVGUST",
     "SEPTEMBAR", "OKTOBAR", "NOVEMBAR", "DECEMBAR"},
    {"一月", "二月", "三月", "四月", "五月", "六月", "七月", "八月", "九月",
     "十月", "十一月", "十二月"},
    {"JANUARI", "FEBRUARI", "MARET", "APRIL", "MEI", "JUNI", "JULI",
     "AGUSTUS", "SEPTEMBER", "OKTOBER", "NOVEMBER", "DESEMBER"},
    {"СІЧЕНЬ", "ЛЮТИЙ", "БЕРЕЗЕНЬ", "КВІТЕНЬ", "ТРАВЕНЬ", "ЧЕРВЕНЬ",
     "ЛИПЕНЬ", "СЕРПЕНЬ", "ВЕРЕСЕНЬ", "ЖОВТЕНЬ", "ЛИСТОПАД", "ГРУДЕНЬ"},
    {"IONAWR", "CHWEFROR", "MAWRTH", "EBRILL", "MAI", "MEHEFIN", "GORFFENNAF",
     "AWST", "MEDI", "HYDREF", "TACHWEDD", "RHAGFYR"},
    {"XANEIRO", "FEBREIRO", "MARZO", "ABRIL", "MAIO", "XUNO", "XULLO",
     "AGOSTO", "SETEMBRO", "OUTUBRO", "NOVEMBRO", "DECEMBRO"},
    {"1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月",
     "11月", "12月"},
    {"1월", "2월", "3월", "4월", "5월", "6월", "7월", "8월", "9월", "10월",
     "11월", "12월"},
    {"ינואר", "פברואר", "מרץ", "אפריל", "מאי", "יוני", "יולי", "אוגוסט",
     "ספטמבר", "אוקטובר", "נובמבר", "דצמבר"},
    {"JANUARY", "FEBRUARY", "MARCH", "APRIL", "MAY", "JUNE", "JULY",
     "AUGUST", "SEPTEMBER", "OCTOBER", "NOVEMBER", "DECEMBER"}};

const uint8_t date_part_order[LANGUAGE_COUNT][3] = {
    {DATE_PART_WEEKDAY, DATE_PART_MONTH, DATE_PART_DATE},  // English (US)
    {DATE_PART_WEEKDAY, DATE_PART_DATE, DATE_PART_MONTH},  // French
    {DATE_PART_WEEKDAY, DATE_PART_DATE, DATE_PART_MONTH},  // German
    {DATE_PART_WEEKDAY, DATE_PART_DATE, DATE_PART_MONTH},  // Spanish
    {DATE_PART_WEEKDAY, DATE_PART_DATE, DATE_PART_MONTH},  // Italian
    {DATE_PART_WEEKDAY, DATE_PART_DATE, DATE_PART_MONTH},  // Dutch
    {DATE_PART_DATE, DATE_PART_MONTH, DATE_PART_WEEKDAY},  // Turkish
    {DATE_PART_WEEKDAY, DATE_PART_DATE, DATE_PART_MONTH},  // Czech
    {DATE_PART_WEEKDAY, DATE_PART_DATE, DATE_PART_MONTH},  // Portuguese
    {DATE_PART_WEEKDAY, DATE_PART_DATE, DATE_PART_MONTH},  // Greek
    {DATE_PART_WEEKDAY, DATE_PART_DATE, DATE_PART_MONTH},  // Swedish
    {DATE_PART_WEEKDAY, DATE_PART_DATE, DATE_PART_MONTH},  // Polish
    {DATE_PART_WEEKDAY, DATE_PART_DATE, DATE_PART_MONTH},  // Slovak
    {DATE_PART_WEEKDAY, DATE_PART_DATE, DATE_PART_MONTH},  // Vietnamese
    {DATE_PART_WEEKDAY, DATE_PART_DATE, DATE_PART_MONTH},  // Romanian
    {DATE_PART_WEEKDAY, DATE_PART_DATE, DATE_PART_MONTH},  // Catalan
    {DATE_PART_WEEKDAY, DATE_PART_DATE, DATE_PART_MONTH},  // Norwegian
    {DATE_PART_WEEKDAY, DATE_PART_DATE, DATE_PART_MONTH},  // Russian
    {DATE_PART_WEEKDAY, DATE_PART_DATE, DATE_PART_MONTH},  // Estonian
    {DATE_PART_WEEKDAY, DATE_PART_DATE, DATE_PART_MONTH},  // Basque
    {DATE_PART_WEEKDAY, DATE_PART_DATE, DATE_PART_MONTH},  // Finnish
    {DATE_PART_WEEKDAY, DATE_PART_DATE, DATE_PART_MONTH},  // Danish
    {DATE_PART_WEEKDAY, DATE_PART_DATE, DATE_PART_MONTH},  // Lithuanian
    {DATE_PART_WEEKDAY, DATE_PART_DATE, DATE_PART_MONTH},  // Slovenian
    {DATE_PART_MONTH, DATE_PART_DATE, DATE_PART_WEEKDAY},  // Hungarian
    {DATE_PART_WEEKDAY, DATE_PART_DATE, DATE_PART_MONTH},  // Croatian
    {DATE_PART_WEEKDAY, DATE_PART_DATE, DATE_PART_MONTH},  // Irish
    {DATE_PART_WEEKDAY, DATE_PART_DATE, DATE_PART_MONTH},  // Latvian
    {DATE_PART_WEEKDAY, DATE_PART_DATE, DATE_PART_MONTH},  // Serbian
    {DATE_PART_MONTH, DATE_PART_DATE, DATE_PART_WEEKDAY},  // Chinese
    {DATE_PART_WEEKDAY, DATE_PART_DATE, DATE_PART_MONTH},  // Indonesian
    {DATE_PART_WEEKDAY, DATE_PART_DATE, DATE_PART_MONTH},  // Ukrainian
    {DATE_PART_WEEKDAY, DATE_PART_DATE, DATE_PART_MONTH},  // Welsh
    {DATE_PART_WEEKDAY, DATE_PART_DATE, DATE_PART_MONTH},  // Galician
    {DATE_PART_MONTH, DATE_PART_DATE, DATE_PART_WEEKDAY},  // Japanese
    {DATE_PART_MONTH, DATE_PART_DATE, DATE_PART_WEEKDAY},  // Korean
    {DATE_PART_WEEKDAY, DATE_PART_DATE, DATE_PART_MONTH},  // Hebrew
    {DATE_PART_WEEKDAY, DATE_PART_DATE, DATE_PART_MONTH}   // English (UK)
};
